package: navbuilder
version: '1.0.6'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/navbuilder

page:
    title: NavBuilder
    perm: navbuilder[]
    pjax: false
    icon: rex-icon fa-bars
    subpages:
            menus: {title: 'Navigationen'}

requires:
    packages:
        structure: '^2.9.0'
        phpmailer: '^2.7.0'
        yform: '>3.3.1,<5'
    redaxo: '^5.9.0'
